import React from 'react';
import PaymentFieldConfigurator from '@/components/PaymentFieldConfigurator';
import type { PaymentSectionProps } from './shared';

export default function PaymentSection({ invoice, lang, t, onChange, autoResizeTextarea, showPaymentFieldConfig, setShowPaymentFieldConfig, isUploadingQRCode, onOpenQRCodePicker, onRemoveQRCode, canvasRef, startDrawing, draw, stopDrawing, signatureInputRef, handleSignatureUpload, clearSignature }: PaymentSectionProps) {
  return (
    <section className="pt-4 border-t border-slate-100 space-y-6">
      <div className="flex justify-between items-center"><span className="text-sm font-semibold text-slate-700">{t.taxRate}</span><input type="number" className="w-20 px-3 py-1 bg-white border border-slate-200 rounded-lg text-right text-sm" value={invoice.taxRate} onChange={(e) => onChange({ taxRate: Number(e.target.value) })} /></div>
      <div className="bg-blue-600 p-4 rounded-xl text-white flex justify-between items-center"><span className="font-bold uppercase text-xs">{t.payable}</span><span className="text-2xl font-black">{new Intl.NumberFormat(lang, { style: 'currency', currency: invoice.currency }).format(invoice.items.reduce((sum, item) => sum + (Number(item.quantity || 0) * Number(item.rate || 0)), 0) * (1 + invoice.taxRate / 100))}</span></div>
      <div className="col-span-full"><div className="flex justify-between items-center mb-3 relative"><div className="flex items-center gap-2"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">{t.paymentInfo}</h3><button onClick={() => onChange({ visibility: { ...invoice.visibility, paymentInfo: !invoice.visibility?.paymentInfo } })} className={`text-xs ${invoice.visibility?.paymentInfo === true ? 'text-blue-600' : 'text-slate-300'}`} title={t.visibility}><i className={`fas fa-toggle-${invoice.visibility?.paymentInfo === true ? 'on' : 'off'} text-lg`}></i></button></div>{invoice.visibility?.paymentInfo === true && <button onClick={() => setShowPaymentFieldConfig(!showPaymentFieldConfig)} className="text-slate-400 hover:text-blue-600 transition-colors" title={t.configurePaymentFields || 'Configure Payment Fields'}><i className="fas fa-cog"></i></button>}{showPaymentFieldConfig && invoice.paymentInfo?.fields && <PaymentFieldConfigurator fields={invoice.paymentInfo.fields} onChange={(newFields) => onChange({ paymentInfo: { ...invoice.paymentInfo, fields: newFields } })} onClose={() => setShowPaymentFieldConfig(false)} lang={lang} />}</div>
        {invoice.visibility?.paymentInfo === true && <>{isUploadingQRCode ? <div className="w-full p-4 border-2 border-dashed border-blue-300 rounded-lg bg-blue-50 mb-4"><div className="flex flex-col items-center gap-2 text-blue-600"><i className="fas fa-circle-notch fa-spin text-2xl"></i><span className="text-xs font-medium">{t.uploadingImage}</span></div></div> : !invoice.paymentInfo?.qrCode ? <button onClick={onOpenQRCodePicker} className="w-full p-4 border-2 border-dashed border-slate-300 rounded-lg hover:border-blue-500 hover:bg-blue-50 transition-all group mb-4"><div className="flex flex-col items-center gap-2 text-slate-400 group-hover:text-blue-600"><i className="fas fa-qrcode text-2xl"></i><span className="text-xs font-medium">{t.uploadQR || 'Upload QR Code'}</span></div></button> : <div className="relative group mb-4"><div className="w-full p-3 border-2 border-slate-200 rounded-lg bg-slate-50"><img src={invoice.paymentInfo.qrCode} alt="QR Code" className="w-full h-40 object-contain" /></div><div className="absolute inset-0 bg-black bg-opacity-0 group-hover:bg-opacity-50 rounded-lg transition-all flex items-center justify-center gap-2 opacity-0 group-hover:opacity-100"><button onClick={onOpenQRCodePicker} className="px-3 py-1.5 bg-blue-600 text-white text-xs font-medium rounded-lg hover:bg-blue-700 transition-colors"><i className="fas fa-sync-alt mr-1"></i>{t.uploadQR?.replace('上傳', '更換').replace('Upload', 'Change') || 'Change'}</button><button onClick={onRemoveQRCode} className="px-3 py-1.5 bg-red-600 text-white text-xs font-medium rounded-lg hover:bg-red-700 transition-colors"><i className="fas fa-trash mr-1"></i>{t.removeQR?.split(' ')[0] || 'Remove'}</button></div></div>}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">{invoice.paymentInfo?.fields?.filter(f => f.visible)?.sort((a, b) => a.order - b.order)?.map((field) => { const updateFieldValue = (value: string) => { const newFields = invoice.paymentInfo?.fields?.map(f => f.id === field.id ? { ...f, value } : f) || []; onChange({ paymentInfo: { ...invoice.paymentInfo, fields: newFields } }); }; return <div key={field.id}>{field.type === 'textarea' ? <textarea ref={autoResizeTextarea} placeholder={field.label} value={field.value} onChange={(e) => updateFieldValue(e.target.value)} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-lg resize-none overflow-hidden text-sm" rows={1} onInput={(e) => { e.currentTarget.style.height = 'auto'; e.currentTarget.style.height = e.currentTarget.scrollHeight + 'px'; }} /> : <textarea ref={autoResizeTextarea} placeholder={field.label} value={field.value} onChange={(e) => updateFieldValue(e.target.value)} className={`w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-lg resize-none overflow-hidden text-sm ${field.id === 'accountNumber' ? 'font-mono' : ''}`} rows={1} onInput={(e) => { e.currentTarget.style.height = 'auto'; e.currentTarget.style.height = e.currentTarget.scrollHeight + 'px'; }} />}</div>; })}</div></>}
      </div>
      <div className="space-y-3"><div className="flex justify-between items-center"><div className="flex items-center gap-2"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">{t.signature}</h3><button onClick={() => onChange({ visibility: { ...invoice.visibility, signature: !invoice.visibility?.signature } })} className={`text-xs ${invoice.visibility?.signature === true ? 'text-blue-600' : 'text-slate-300'}`} title={t.visibility}><i className={`fas fa-toggle-${invoice.visibility?.signature === true ? 'on' : 'off'} text-lg`}></i></button></div>{invoice.visibility?.signature === true && <div className="flex gap-2 items-center"><input type="file" ref={signatureInputRef} onChange={handleSignatureUpload} accept="image/*" className="hidden" id="signature-upload" /><label htmlFor="signature-upload" className="text-[10px] font-bold text-indigo-600 uppercase hover:underline cursor-pointer">📤 Upload</label><button onClick={clearSignature} className="text-[10px] font-bold text-blue-600 uppercase hover:underline">{t.signClear}</button></div>}</div>{invoice.visibility?.signature === true && <div className="bg-slate-50 border-2 border-dashed border-slate-200 rounded-2xl overflow-hidden relative animate-in slide-in-from-top-2 duration-200"><canvas ref={canvasRef} width={1000} height={400} onMouseDown={startDrawing} onMouseMove={draw} onMouseUp={stopDrawing} onMouseLeave={stopDrawing} onTouchStart={startDrawing} onTouchMove={draw} onTouchEnd={stopDrawing} className="w-full h-[200px] cursor-crosshair touch-none" />{!invoice.sender.signature && <div className="absolute inset-0 flex items-center justify-center pointer-events-none text-slate-300 text-xs font-medium">{t.signPlaceholder}</div>}</div>}</div>
      <div className="space-y-3 pt-2"><div className="flex justify-between items-center"><div className="flex items-center gap-2"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-400">{t.disclaimerText || 'Disclaimer / Notice'}</h3><button onClick={() => onChange({ visibility: { ...invoice.visibility, disclaimer: invoice.visibility?.disclaimer === false } })} className={`text-xs ${invoice.visibility?.disclaimer !== false ? 'text-blue-600' : 'text-slate-300'}`} title={t.visibility}><i className={`fas fa-toggle-${invoice.visibility?.disclaimer !== false ? 'on' : 'off'} text-lg`}></i></button></div></div>{invoice.visibility?.disclaimer !== false && <textarea placeholder="e.g., This is a computer generated document and no signature is required." value={invoice.sender.disclaimerText || ''} onChange={(e) => onChange({ sender: { ...invoice.sender, disclaimerText: e.target.value } })} className="w-full px-4 py-2 bg-slate-50 border border-slate-200 rounded-lg h-20 text-sm resize-none" />}</div>
    </section>
  );
}
