export const SCHOOL_POSTER_A4_WIDTH_MM = 210;
export const SCHOOL_POSTER_A4_HEIGHT_MM = 297;
export const SCHOOL_POSTER_A4_ASPECT_RATIO = SCHOOL_POSTER_A4_WIDTH_MM / SCHOOL_POSTER_A4_HEIGHT_MM;

export const SCHOOL_POSTER_PREVIEW_BASE_WIDTH = 794;
export const SCHOOL_POSTER_PREVIEW_BASE_WIDTH_REM = SCHOOL_POSTER_PREVIEW_BASE_WIDTH / 16;
